theme: minima
title: **Product Research & Development**
author: GitHub User
email: prgNet@openspc.com
description: > # this means to ignore newlines until "baseurl:"
  We are expecting site changes that are engine searchable as well as feed.xml 
  ## experimenting with markdown hashtagging with double hashes on each end of this sentence ##

# social links

github_username:  osWes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
